# Generated by Django 4.2.18 on 2025-03-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FisherMan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "additional_data",
                    models.TextField(blank=True, default="{}", null=True),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, db_index=True, max_length=2500, null=True
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_dangerous", models.BooleanField(db_index=True, default=False)),
                ("is_docked", models.BooleanField(db_index=True, default=False)),
                ("is_fishing", models.BooleanField(db_index=True, default=False)),
                ("last_successful_catch", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("store_catching_info", models.BooleanField(default=True)),
                (
                    "strategy",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FishType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                ("docked_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_dangerous", models.BooleanField(default=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("problem", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "WAITING"),
                            ("SAILING", "SAILING"),
                            ("RETURNED", "RETURNED"),
                            ("DAMAGED", "DAMAGED"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                ("time_spent", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShipConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "key",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("val", models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Net",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deployed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("fishing_info", models.TextField(blank=True, null=True)),
                ("is_dangerous", models.BooleanField(default=False)),
                ("problem", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("CAST", "CAST"),
                            ("IN-USE", "IN-USE"),
                            ("FISHED", "FISHED"),
                            ("DAMAGED", "DAMAGED"),
                            ("EMPTY", "EMPTY"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("time_in_water", models.IntegerField(blank=True, null=True)),
                (
                    "fish_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nets",
                        to="fleet.fishtype",
                    ),
                ),
                (
                    "fisherman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nets",
                        to="fleet.fisherman",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nets",
                        to="fleet.ship",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fisherman",
            name="fish_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fishers",
                to="fleet.fishtype",
            ),
        ),
        migrations.CreateModel(
            name="Fish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("caught_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_dangerous", models.BooleanField(default=False)),
                (
                    "link",
                    models.URLField(
                        blank=True, db_index=True, max_length=2500, null=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500)),
                ("tagged", models.BooleanField(db_index=True, default=False)),
                ("tracking_id", models.CharField(max_length=2500, unique=True)),
                (
                    "fish_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fishes",
                        to="fleet.fishtype",
                    ),
                ),
                (
                    "fisherman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fishes",
                        to="fleet.fisherman",
                    ),
                ),
                (
                    "net",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fishes",
                        to="fleet.net",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fishes",
                        to="fleet.ship",
                    ),
                ),
            ],
        ),
    ]
