# Generated by Django 4.1.1 on 2024-12-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConfigValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "key",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                ("val", models.CharField(blank=True, max_length=250, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteConf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("extra_data_json", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="las la-question-circle",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_locked", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("ns_flag", models.BooleanField(db_index=True, default=False)),
                (
                    "scraper_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_confs",
                        to="crawler.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("elapsed_time", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("WAITING", "WAITING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("ERROR", "ERROR"),
                            ("NO-ITEM", "NO-ITEM"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "site_conf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="crawler.siteconf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("is_bookmarked", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(db_index=True, max_length=500)),
                ("unique_key", models.CharField(max_length=2500, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "url",
                    models.URLField(
                        blank=True, db_index=True, max_length=2500, null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crawler.job",
                    ),
                ),
                (
                    "site_conf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crawler.siteconf",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "site_conf"], name="crawler_job_status_5473fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["is_bookmarked", "site_conf"],
                name="crawler_ite_is_book_f52e2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["name", "created_at"], name="crawler_ite_name_10c853_idx"
            ),
        ),
    ]
