# Generated by Django 4.1.1 on 2024-12-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconf",
            name="extra_data_json",
            field=models.TextField(blank=True, default="{}", null=True),
        ),
    ]
